import React from 'react';
import { Button, Row, Col, Form } from "react-bootstrap";
import { EditorComponent, FileUploadComponent, ImageSortable } from 'js/components/common';
import classnames from 'classnames';


export const CreateCategory = () => {

    return (
        <section className="crearte-products-section">
            <div className="generic-page-header">
                <h2 className="page-head my-0">Create Category</h2>
                <Button
                    className="add-new-btn"
                //onClick={() => history.push('/admin/create-product')}
                >
                    Save Changes
          		</Button>
            </div>
            <Row className="mt-5">
                <Col>
                    <div className="dash_activity_card">
                        <h5 className="card-title">General Informations</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="input-area w-50">
                                <Form.Control type="text" placeholder="Category Name" />
                            </div>
                        </div>
                        <div className="editor-wrapper">
                            <div className={classnames("editor-outer-wrap")}>
                                <EditorComponent
                                    advertisement
                                    id="description"
                                // content={state.description}
                                // onChange={(content) => handleChange(content, 'description')}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <div className="d-flex justify-content-between">
                            <h5 className="card-title">Background Images (Optional)</h5>
                        </div>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="upload-photo-wrap">
                                <div className="photo-uploader">
                                    <FileUploadComponent
                                        entity_type='TripMedia'
                                        multiple={true}
                                        max={10}
                                        accepted={['image/*']}
                                    // onSuccess={props.onAddNewFiles}
                                    />
                                </div>
                                <ImageSortable files={[{ attachment_url: 'https://picsum.photos/200/300' }, { attachment_url: 'https://picsum.photos/200/200' }, { attachment_url: 'https://picsum.photos/200/204' }]} />
                                <div className="drag-drop-text">
                                    <h4>
                                        <img src="/images/admin/global/arrow.svg" alt="" />
                                        Drag and drop photos to best represent your listing.
                                    </h4>
                                </div>
                                <div className="drag-drop-text">
                                    <h4>
                                        <img src="/images/admin/global/info.svg" alt="" />
                                        You can only add upto 10 files at a time, max Size of file should be less than 2mb
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <h5 className="card-title">Search Engine Preview</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <span className="mb-3">Add search engine title and description to make this product easier to find</span>
                            <div className="input-area mt-3">
                                <Form.Control type="text" placeholder="Search Engine Title" />
                            </div>
                            <span className="reminder-text ml-2 mt-1">If empty, the preview shows what will be autogenerated.</span>

                            <div className="input-area mt-3">
                                <Form.Control
                                    as="textarea"
                                    rows={3}
                                    placeholder="Note"
                                />
                            </div>
                            <span className="reminder-text ml-2">If empty, the preview shows what will be autogenerated.</span>
                        </div>
                    </div>
                </Col>
            </Row>
            {/* 
            <Row className="mt-5 d-flex justify-content-center">
                <Button
                    className="add-new-btn text-uppercase"
                    //onClick={() => history.push('/admin/create-product')}
                >
                    Create Product
          			</Button>
            </Row> */}
        </section>
    )
}