import React from 'react';
import { Button, Table, Row, Col, Form } from "react-bootstrap";
import Select from "react-select";
import { EditorComponent, FileUploadComponent, ImageSortable } from 'js/components/common';
import classnames from 'classnames';


export const CreateProduct = () => {


    return (
        <section className="crearte-products-section">
            <div className="generic-page-header">
                <h2 className="page-head my-0">Create Product</h2>
                <Button
                    className="add-new-btn"
                //onClick={() => history.push('/admin/create-product')}
                >
                    Save Changes
          		</Button>
            </div>
            <Row className="mt-5">
                <Col md={8}>
                    <div className="dash_activity_card">
                        <h5 className="card-title">General Informations</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="input-area">
                                <Form.Control type="text" placeholder="Name" />
                            </div>
                        </div>
                        <div className="editor-wrapper">
                            <div className={classnames("editor-outer-wrap")}>
                                <EditorComponent
                                    advertisement
                                    id="description"
                                // content={state.description}
                                // onChange={(content) => handleChange(content, 'description')}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <div className="d-flex justify-content-between">
                            <h5 className="card-title">Images</h5>
                        </div>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="upload-photo-wrap">
                                <div className="photo-uploader">
                                    <FileUploadComponent
                                        entity_type='TripMedia'
                                        multiple={true}
                                        max={10}
                                        accepted={['image/*']}
                                    // onSuccess={props.onAddNewFiles}
                                    />
                                </div>
                                <ImageSortable files={[{attachment_url:'https://picsum.photos/200/300'},{attachment_url:'https://picsum.photos/200/200'},{attachment_url:'https://picsum.photos/200/204'}]}/>
                                <div className="drag-drop-text">
                                    <h4>
                                        <img src="/images/admin/global/arrow.svg" alt="" />
                                        Drag and drop photos to best represent your listing.
                                    </h4>
                                </div>
                                <div className="drag-drop-text">
                                    <h4>
                                        <img src="/images/admin/global/info.svg" alt="" />
                                        You can only add upto 10 files at a time, max Size of file should be less than 2mb
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <h5 className="card-title">Pricing</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="input-area">
                                <Form.Control type="number" placeholder="Price" />
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <h5 className="card-title">Search Engine Preview</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <span className="mb-3">Add search engine title and description to make this product easier to find</span>
                            <div className="input-area mt-3">
                                <Form.Control type="text" placeholder="Search Engine Title" />
                            </div>
                            <span className="reminder-text ml-2">If empty, the preview shows what will be autogenerated.</span>

                            <div className="text-area mt-3">
                                <Form.Control type="textarea" placeholder="Search Engine Description" />
                            </div>
                            <span className="reminder-text ml-2">If empty, the preview shows what will be autogenerated.</span>
                        </div>
                    </div>
                </Col>
                <Col md={4}>
                    <div className="dash_activity_card">
                        <h5 className="card-title">Organize Product</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="custom-react-select w-100">
                                <Select
                                    placeholder="Product Type"
                                    className="react-select-container"
                                    classNamePrefix="react-select"
                                //options={BulkActionItems}
                                //styles={styles}
                                // onChange={(e: any) => {
                                //     setBulkAction(e.value);
                                // }}
                                />
                            </div>
                            <hr className="MuiDivider-root" />
                            <div className="custom-react-select w-100">
                                <Select
                                    placeholder="Category"
                                    className="react-select-container"
                                    classNamePrefix="react-select"
                                //options={BulkActionItems}
                                //styles={styles}
                                // onChange={(e: any) => {
                                //     setBulkAction(e.value);
                                // }}
                                />
                            </div>
                            <hr className="MuiDivider-root" />
                            <div className="custom-react-select w-100">
                                <Select
                                    placeholder="Collections"
                                    className="react-select-container"
                                    classNamePrefix="react-select"
                                //options={BulkActionItems}
                                //styles={styles}
                                // onChange={(e: any) => {
                                //     setBulkAction(e.value);
                                // }}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="dash_activity_card mt-4">
                        <h5 className="card-title">Visibility</h5>
                        <hr className="MuiDivider-root" />
                        <div className="card-data-wrapper">
                            <div className="custom-radio-button w-100">
                                <Form.Check
                                    type='radio'
                                    id={`default-1`}
                                    label='Visible'
                                    inline
                                    name="visibility"
                                />
                            </div>
                            <div className="custom-radio-button w-100">
                                <Form.Check
                                    type='radio'
                                    id={`default-2`}
                                    label='Hidden'
                                    inline
                                    name="visibility"
                                />
                            </div>
                        </div>
                    </div>
                </Col>
            </Row>
            {/* 
            <Row className="mt-5 d-flex justify-content-center">
                <Button
                    className="add-new-btn text-uppercase"
                    //onClick={() => history.push('/admin/create-product')}
                >
                    Create Product
          			</Button>
            </Row> */}
        </section>
    )
}